version: '3.7'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_CONFIG_LOCATION=/app/application-docker.properties
      - logging.level.root=INFO
      - logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
      - logging.level.org.springframework.cloud.gateway=TRACE
    networks:
      - my-network

networks:
  my-network:
    name: my-network  # Specify custom network name
    driver: bridge
