version: '3.7'

services:
  eureka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: localhost
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
      EUREKA_CLIENT_FETCH_REGISTRY: false
    networks:
      - my-network

networks:
  my-network:
    name: my-network  # Specify custom network name
    driver: bridge
